(cl:defpackage robot_controllers_msgs-msg
  (:use )
  (:export
   "<DIFFDRIVELIMITERPARAMS>"
   "DIFFDRIVELIMITERPARAMS"
   "<CONTROLLERSTATE>"
   "CONTROLLERSTATE"
   "<QUERYCONTROLLERSTATESACTIONRESULT>"
   "QUERYCONTROLLERSTATESACTIONRESULT"
   "<QUERYCONTROLLERSTATESACTIONGOAL>"
   "QUERYCONTROLLERSTATESACTIONGOAL"
   "<QUERYCONTROLLERSTATESGOAL>"
   "QUERYCONTROLLERSTATESGOAL"
   "<QUERYCONTROLLERSTATESACTION>"
   "QUERYCONTROLLERSTATESACTION"
   "<QUERYCONTROLLERSTATESRESULT>"
   "QUERYCONTROLLERSTATESRESULT"
   "<QUERYCONTROLLERSTATESACTIONFEEDBACK>"
   "QUERYCONTROLLERSTATESACTIONFEEDBACK"
   "<QUERYCONTROLLERSTATESFEEDBACK>"
   "QUERYCONTROLLERSTATESFEEDBACK"
  ))

